# Project Name
TARGET = DAISY_SEED_SCREAM

# Sources
CPP_SOURCES = ./src/possible_implimentation.cpp

#C_INCLUDES += ./inc/

# Library Locations
LIBDAISY_DIR = ../DaisyExamples/libDaisy/
DAISYSP_DIR = ../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile